<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blog.proto

namespace Blog;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Response message to Index method.
 *
 * Generated from protobuf message <code>blog.ListPostsResponse</code>
 */
class ListPostsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .blog.PostResponse posts = 1;</code>
     */
    private $posts;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Blog\PostResponse[]|\Google\Protobuf\Internal\RepeatedField $posts
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Blog::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .blog.PostResponse posts = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPosts()
    {
        return $this->posts;
    }

    /**
     * Generated from protobuf field <code>repeated .blog.PostResponse posts = 1;</code>
     * @param \Blog\PostResponse[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPosts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Blog\PostResponse::class);
        $this->posts = $arr;

        return $this;
    }

}

